# Generated by Django 4.2.5 on 2023-09-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
  initial = True

  dependencies = [
    ('category', '0003_rename_descriptipon_category_description'),
  ]

  operations = [
    migrations.CreateModel(
      name='Product',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('name', models.CharField(max_length=200, unique=True)),
        ('slug', models.SlugField(max_length=200, unique=True)),
        ('description', models.TextField(blank=True, max_length=1000)),
        ('price', models.IntegerField()),
        ('image', models.ImageField(blank=True, upload_to='photos/products/')),
        ('stock', models.IntegerField()),
        ('is_available', models.BooleanField(default=True)),
        ('create_date', models.DateTimeField(auto_now_add=True)),
        ('update_date', models.DateTimeField(auto_now=True)),
        ('category', models.ForeignKey(on_delete=models.SET(None), to='category.category')),
      ],
    ),
  ]
