# Generated by Django 4.2.5 on 2023-09-23 23:36

from django.db import migrations


class Migration(migrations.Migration):
  dependencies = [
    ('category', '0002_alter_category_slug'),
  ]

  operations = [
    migrations.RenameField(
      model_name='category',
      old_name='descriptipon',
      new_name='description',
    ),
  ]
